// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukQlykJq5Ryq5EKnWE_43qUY0ch8MR8E',
    appId: '1:535384356646:web:d488cbe5a81135e92b33e7',
    messagingSenderId: '535384356646',
    projectId: 'studyapp-28681',
    authDomain: 'studyapp-28681.firebaseapp.com',
    storageBucket: 'studyapp-28681.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhhkEYHn_4wXIS53AzcRDGDtBkajeOHL8',
    appId: '1:535384356646:android:aef52579dcf95fbc2b33e7',
    messagingSenderId: '535384356646',
    projectId: 'studyapp-28681',
    storageBucket: 'studyapp-28681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTsXPOj8X5Znj1mDtGSuUhPcBS9TKmHo',
    appId: '1:535384356646:ios:5b1ae1ceaac16ab62b33e7',
    messagingSenderId: '535384356646',
    projectId: 'studyapp-28681',
    storageBucket: 'studyapp-28681.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTsXPOj8X5Znj1mDtGSuUhPcBS9TKmHo',
    appId: '1:535384356646:ios:5b1ae1ceaac16ab62b33e7',
    messagingSenderId: '535384356646',
    projectId: 'studyapp-28681',
    storageBucket: 'studyapp-28681.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBukQlykJq5Ryq5EKnWE_43qUY0ch8MR8E',
    appId: '1:535384356646:web:dcfaa503410ebd782b33e7',
    messagingSenderId: '535384356646',
    projectId: 'studyapp-28681',
    authDomain: 'studyapp-28681.firebaseapp.com',
    storageBucket: 'studyapp-28681.firebasestorage.app',
  );
}
